### ISSUE TITLE
onos-cli panic because of no pod

### ISSUE THREAD

**Issue by yeya24** [onosproject/onos-test#161]
logs for this bug
``` shell
./onit onos-cli   
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/onosproject/onos-test/pkg/onit/cli.getOnosCliCommand.func1(0xc0003f1180, 0x6869388, 0x0, 0x0)
        /Users/yeya24/hub/gowork/onos-test/pkg/onit/cli/ssh.go:47 +0x2a1
github.com/spf13/cobra.(*Command).execute(0xc0003f1180, 0x6869388, 0x0, 0x0, 0xc0003f1180, 0x6869388)
        /Users/yeya24/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003de000, 0xc0003de000, 0xc000127f88, 0x400769f)
        /Users/yeya24/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/yeya24/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/yeya24/hub/gowork/onos-test/cmd/onit/main.go:33 +0x40
```

How to reproduce this bug:
1. ./onit create cluster test
2. Then use CTRL+D to stop the process
3. Use ./onit onos-cli

Actually you can reproduce this bug by manually delete the onos-cli pod in your current ns as well.

Since I stop the cluster creating process, the onos-cli pod is not created. Then the onos-cli cmd get panic. We should ensure this pod is in that namespace, otherwise return an err.

**Comment by yeya24** [comment]
Same panic for onos fetch as well
``` shell
./onit fetch logs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5230916]

goroutine 1 [running]:
github.com/onosproject/onos-test/pkg/onit/setup.(*TestSetup).FetchLogs(0xc00052bbd8)
        /Users/yeya24/hub/gowork/onos-test/pkg/onit/setup/cluster.go:269 +0x5b6
github.com/onosproject/onos-test/pkg/onit/cli.getFetchLogsCommand.func1(0xc0003d1680, 0x6869388, 0x0, 0x0)
        /Users/yeya24/hub/gowork/onos-test/pkg/onit/cli/fetch.go:66 +0x229
github.com/spf13/cobra.(*Command).execute(0xc0003d1680, 0x6869388, 0x0, 0x0, 0xc0003d1680, 0x6869388)
        /Users/yeya24/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013ec80, 0xc00013ec80, 0xc000129f88, 0x400769f)
        /Users/yeya24/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/yeya24/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/yeya24/hub/gowork/onos-test/cmd/onit/main.go:33 +0x40

```

**Comment by adibrastegarnia** [comment]
@yeya24 
In the new version of onit, it is likely this error already handled because  we use an API to create the cluster but it is still a work in progress and not fully tested but you are right we need to make sure if creating of cluster is not successful because of any reasons (i.e. by stopping the process), we should delete the current cluster if it is possible (i.e. the one which we are creating) to release the resources that are created so far or handle the above error properly.

**Comment by adibrastegarnia** [comment]
@yeya24 
will be closed this issue since it is already resolved in the new version of onit. Feel free to open it again if you still have problems.
